# This is a basic workflow to help you get started with Actions

name: collectionRun with HTML

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron:  '0 8,20 * * 1,2,3,4,5,6'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: List folder
        run: ls -a
        
      - name: Install Htmlextra reporter
        run: npm install -g newman-reporter-htmlextra
        
      - name: Run Collection with CLI
        run: newman run Trello.postman_collection.json 
        
      - name: Run Collection with API
        run: newman run https://api.getpostman.com/collections/7f84364f-cf68-4e21-a6e8-4fff33b385d9?apikey=PMAK-62b558522fc64d315bea82d3-148808b490bf1af07d003e0da6bc26d965 -r htmlextra --reporter-htmlextra-export "./"
      
      - name: List folder
        run: ls -a
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: htmlreport
          path: "*.html"

